### ISSUE TITLE
Integration with Beego

### ISSUE THREAD

**Issue by ihash** [qor/qor#104]
Hi

I have exactly what ever explained in the FAQ to integrate admin with beego but I get 404.
Also I can run qor-example correctly...
What should I do?
2015/09/21 14:34:59 [router.go:854] [D] | GET        | /admin                                   | 424.265µs        | notmatch   |

**Comment by amirrpp** [comment]
its work
    func main() {
        mux := http.NewServeMux()
        Admin.MountTo("/admin", mux)

        mux.HandleFunc("/login", controllers.LoginHandler)
        mux.HandleFunc("/logout", controllers.LogoutHandler)

        beego.Handler("/admin/*", mux)
        beego.Handler("/admin", mux)
        beego.Handler("/login", mux)
        beego.Handler("/logout", mux)

        beego.SetStaticPath("/system", "public/system")
        beego.SetStaticPath("/assets", "public/assets")

        beego.Router("/books/", &controllers.ListBooksController{})
        beego.Router("/books/:id", &controllers.ViewBooksController{})

        beego.Run()
    }

**Comment by jinzhu** [comment]
good to see it works ;)

**Comment by ihash** [comment]
Thanks a lot! Now it works...
