### ISSUE TITLE
Support editing datetime

### ISSUE THREAD

**Issue by bodhi** [qor/qor#111]
In the admin, a `time.Time` field uses a date selector as the editor, there's no way to edit the time portion of the field.

**Comment by jinzhu** [comment]
@bodhi I guess you already know this, the form type has `date`, `datetime`, the `datetime` could be used to edit time, but the js plugin doesn't support this.

@jasonweng we need to update the datepicker plugin to handle time, I remember we have researched some choices, not sure what's the decision.

http://simeonc.github.io/sc-date-time/material.html

This one looks good to me, but seems like based on AngularJS, not sure if we could port it to mdl. could you research this?

**Comment by bodhi** [comment]
Ah, I didn't notice that Go doesn't have a date type!
