### ISSUE TITLE
problem with Nested Resource and router

### ISSUE THREAD

**Issue by marcoscleison** [qor/qor#135]
Hallo, I have a problem with Qor nested resource. When a set the Rosouce for nested, some urls are unregistred. Let me explain:
I have two models:

type Order struct {
	gorm.Model
        
       value float32
	
        Plans        []Plan
	transition.Transition
}

And the model

type Plan struct {
	gorm.Model
	Name                 string
	Tipe                 string
}
I created menu setup:

	plans := Adm.AddResource(&Plan{}, &admin.Config{Menu: []string{"Plans"}})

        order:=Adm.AddResource(&Order{}, &admin.Config{Menu: []string{"Order"}})
	order.Meta(&admin.Meta{Name: "Plans", Type:"collection_edit", Resource: plans})

The app is compiled without errors and the Plans form is nested in Order form, as  wished, however the url /admin/plans gives 404 error code.
When I register without nested, the url works property:

	plans := Adm.AddResource(&Plan{}, &admin.Config{Menu: []string{"Plans"}})

        order:=Adm.AddResource(&Order{}, &admin.Config{Menu: []string{"Order"}})
.
How should i solve this issue?
Thank you!

**Comment by jinzhu** [comment]
Hi @marcoscleison 

Nested Resource need to has a valid association, refer https://github.com/jinzhu/gorm#associations

For your example, it lacks of a foreign key.

**Comment by marcoscleison** [comment]
Thank you so much.
