### ISSUE TITLE
Question about dB.

### ISSUE THREAD

**Issue by joeblew99** [qor/qor#151]
What's the preferred dB to use ?
Postresql or mysql. 
I just noticed that the example your working on uses mysql.

Also I believe your using an ORM. Are there any blockers to switching databases on my side ? Just want to check because I am thinking about trying out cockroachdb, which uses the same binary api as postresql.

Thanks in advance

**Comment by vefaliahmet** [comment]
Gorm is not supporting cockroachdb.you can change database from config file.

https://github.com/qor/qor-example/blob/master/config/database.example.yml

**Comment by joeblew99** [comment]
Thank you. That's what I needed
