### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by joeblew99** [qor/qor#152]
It looks like there is no logging in the code.

From a brief look all i can see if StDOut logs statements.
For me, no logging is suicide to use this library. You have to know what your systems are doing, and if they are having issues.

Logrus is often used. There are other too, but so far Logrus is a good one that has gotten me far.

Is there an thoughts, advice, roadmap etc on this.

**Comment by vefaliahmet** [comment]
you can use beego logs library.

https://github.com/astaxie/beego/tree/master/logs

**Comment by joeblew99** [comment]
Sure but the problem is not that. It's the fact that no logging statement even exist in the code
