### ISSUE TITLE
Error admin context

### ISSUE THREAD

**Issue by grengojbo** [qor/qor#154]
/Users/jbo/go/src/github.com/qor/qor/admin/context.go:137
**template: publish_drafts.tmpl:20: function "rt" not defined**
/Users/jbo/go/src/github.com/qor/qor/utils/utils.go:193 (0x2b6cb7)
	ExitWithMsg: debug.PrintStack()
........

**Comment by jinzhu** [comment]
Hi @grengojbo 

Thank you for your report, this should been fixed.
