### ISSUE TITLE
Kanban view for state

### ISSUE THREAD

**Issue by happierall** [qor/qor#155]
oDoo erp have Kanban view for state of order - it's simple and powerful for orders management.
See [video](https://www.youtube.com/watch?v=rtFi-R4RF-Q: 
or [screenshot](http://i1-linux.softpedia-static.com/screenshots/Bitnami-Odoo-Stack_1.png)
oDoo is amazing, but it's have python, not go.

Your admin panel have kanban style view?
How can I add it to the admin panel (easy)?

**Comment by ericwo** [comment]
> Your admin panel have kanban style view?

Sorry, we don't have kanban style view for admin.
