### ISSUE TITLE
Issue with pointer meta

### ISSUE THREAD

**Issue by derlaft** [qor/qor#161]
```
type Link struct {
    gorm.Model
}
type SampleModel struct {
    gorm.Model

    GoodLinkID sql.NullInt64
    GoodLink Link

    BadLinkID sql.NullInt64
    BadLink *Link
}
```

When I add this sample model to QOR GoodLink works well, while BadLink throws this error in template:

```
Get error when render template github.com/qor/qor/admin/views/metas/form/select_one.tmpl meta BadLink: reflect: call of reflect.Value.Interface on zero Value
```

**Comment by derlaft** [comment]
Finally, could be able to get a backtrace of error: https://gist.github.com/derlaft/117ba3684002d39c010b

The issue seems to be in gorm

**Comment by jinzhu** [comment]
Hi @derlaft 

Are you still getting this issue?

**Comment by derlaft** [comment]
Hi, @jinzhu 

Yes, I do. Patching gorm (in closed related issue) partly helps, but it seems that the problem is deeper.

**Comment by derlaft** [comment]
There are few problems:

1) When displaying an exiting meta, ``BadLink`` is initialised with nil. Then, qor [passes this nil](https://github.com/qor/qor/blob/master/resource/meta.go#L171)  (which in ``f.Field.Addr().Interface()`` to gorm which panics because of this (and panic quietly absorbed by smth and not logged). Gorm patch helps for this.

2) When displaying a resource creation dialog.I am not sure where it happens, but patching [this](https://github.com/qor/qor/blob/master/admin/meta.go#L246) with ``return ""`` helps.
