### ISSUE TITLE
貌似发现一个错误

### ISSUE THREAD

**Issue by 756445638** [qor/qor#163]
Admin.AddResource(&models.ContactUs{}, &admin.Config{Singleton: true})
&admin.Config{Singleton: true}这个配置使这个资源成为单条
但当数据库一条记录都没有的时候，就会产生一个404错误

**Comment by jinzhu** [comment]
@756445638 你是用的最新的 qor 么？我记得我们这个问题已经修复了。

**Comment by 756445638** [comment]
用的是你们最新的example还是有这个问题，拍了个小视频
http://screencast.com/t/8JV1qnjv

**Comment by jinzhu** [comment]
我试了下最新的版本，应该是好用的了，你再把所有的版本都更新下，试试看看？
