### ISSUE TITLE
slideout panel is broken in firefox

### ISSUE THREAD

**Issue by derlaft** [qor/qor#167]
Webkit-based browser: [screenshot_20160303_001807](https://cloud.githubusercontent.com/assets/852606/13475715/7970a820-e0d5-11e5-84d6-cbf3931a519a.png)
Firefox: [screenshot_20160303_001741](https://cloud.githubusercontent.com/assets/852606/13475719/7cb3d5fc-e0d5-11e5-8a90-0f17fe46e44a.png)

There were no recent commits in https://github.com/qor/qor-exampe, so posting it here

**Comment by derlaft** [comment]
Hmm. This work in my app. Seems to be qor-example issue.

**Comment by derlaft** [comment]
Oh! I've found how to reproduce it: editing is broken only if ShowAttrs are set

**Comment by derlaft** [comment]
Or everything is fine... Sorry for the troubling

(in demo it still does not work)

**Comment by jinzhu** [comment]
seems works in my latest firefox
