### ISSUE TITLE
Add link to edit ForeignKey object

### ISSUE THREAD

**Issue by ianberdin** [qor/qor#169]
![2016-03-17 00-06-06 products - qor demo](https://cloud.githubusercontent.com/assets/2521933/13828731/24c7862c-ebd4-11e5-9bec-656c2514aaf0.png)
Add link to edit ForeignKey object. 
It's important feature for shop, where 100+ objects.

**Comment by jinzhu** [comment]
Yes, this would be helpful, we are going to support this in the future.

**Comment by happierall** [comment]
When?
