### ISSUE TITLE
Password field problem

### ISSUE THREAD

**Issue by dmitry-udod** [qor/qor#180]
Hello, 

When I edit the password field in admin I see plain user password and this password will be save in database. Please see attach.

![screenshot from 2016-08-16 17 58 34](https://cloud.githubusercontent.com/assets/4639175/17703660/2b854d8a-63db-11e6-852f-1035045c43a3.png)

Best Regards,
Dmitry

**Comment by Jeweller-Tsai** [comment]
Hi @dmitry-udod 

The problem is fixed. The details are here https://github.com/qor/qor-example/commit/a50e1a62bb34873f437e12a792487f13ca361bfa

Thanks again!
