### ISSUE TITLE
Can QOR be used for multi sellers ecommerce sites?

### ISSUE THREAD

**Issue by tonyalaribe** [qor/qor#181]
Can QOR be used for ecommerce sites like amazon.com or aliexpress.com? Where multiple sellers can signup and sell their products, while also managing their products from a dashboard. I cant see such support on the admin dashboard

**Comment by sebastianmacias** [comment]
+1

**Comment by coreform** [comment]
You have the power to anything you want with QOR...it is really only limited by your imagination, abilities, time, and resources. If something is missing, you can add the feature and make a pull-request to contribute to a better QOR in the future.
