### ISSUE TITLE
Some inspiration from other ecommerce projects

### ISSUE THREAD

**Issue by kifirkin** [qor/qor#194]
I'll just post it here(some frameworks that I've used before `qor`) :smile: 
They have some ideas to look at. But also have too many cons to use them
- https://www.pimcore.org/ (con: PHP, slow; pro: reach admin)
- https://reactioncommerce.com/ (con: nodejs, young; pro: nice inline edit almost everything, realtime)
- https://www.totaljs.com/eshop/ (con: nodejs, young, buggy; pro: very easy to learn)
- https://spreecommerce.com/ (con: slow; pro: many features)
- https://www.shuup.com/en/ (con: slow, python; pro: many features, easy to learn)
- http://apostrophecms.org/ (con: just cms; pro: super modular)
- https://github.com/yoonic/atlas (con: nodejs. only api; pro: swagger)

**Comment by jinzhu** [comment]
Thank you, I will look into them ;)

BTW, QOR will integrate with swagger also, hope this could happen soon ;)

**Comment by alexmironof** [comment]
@jinzhu Thanks for the reply! Yeah swagger is really cool tool! Many big corporations use it, because it gives nicely documented api and fronend developers could consume it easily

**Comment by alexmironof** [comment]
@jinzhu There are some interesting articles on `reactioncommerce` blog.

https://blog.reactioncommerce.com/products-part-3/
