### ISSUE TITLE
Conflicts with qor-example installation

### ISSUE THREAD

**Issue by evivas86** [qor/qor#196]
Hello, i'm trying to install qor usin the command 
`go get -u github.com/qor/qor-example`
this throw me the next message 

```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/qor/qor-example: exit status 1
```

what i'm doing worng?

**Comment by jinzhu** [comment]
Hello,

This might be caused by you made some changes on your local, could you just stash your local changes or just delete qor from your GOPATH and retry it.


Refer: https://github.com/golang/oauth2/issues/201 https://github.com/Microsoft/vscode-go/issues/534
