### ISSUE TITLE
Menu can not support 中文

### ISSUE THREAD

**Issue by smartdriver001** [qor/qor#198]
when i code like this 
user := Admin.AddResource(&User{}, &admin.Config{Menu: []string{"用户管理"}, Name:"用户"})
then it will happened like this
http://localhost:9000/admin/用%EF%BF%BD%EF%BF%BD%EF%BF%BD

404 page not found

How can I support in  chinese ??

**Comment by jinzhu** [comment]
You could use `i18n` to translate the menu for now, but we are working on to support Chinese in the menu w/o i18n

**Comment by smartdriver001** [comment]
Thank you, hope to support Chinese as soon as possible @jinzhu

**Comment by jinzhu** [comment]
This should been supported for a while.
