### ISSUE TITLE
github.com/qor/admin/route.go:94: undefined: sort.SliceStable

### ISSUE THREAD

**Issue by dinboo** [qor/qor#199]
![screen shot 2017-04-30 at 11 29 53 am](https://cloud.githubusercontent.com/assets/22538657/25561505/6c004b3a-2d98-11e7-84fb-9fce61547a10.png)
I was update package qor and has a error. :(

**Comment by bodhi** [comment]
`sort.SliceStable` was introduced in Go 1.8. Upgrading should fix this issue for you?

**Comment by dinboo** [comment]
thank you :)
