### ISSUE TITLE
Issue with i18n function with database backend

### ISSUE THREAD

**Issue by vincent178** [qor/qor#205]
I create a repo which is a minimal reproducible code https://github.com/vincent178/qor_test/blob/master/main.go

I don't know if I didn't use it correctly or it is a bug?

Thanks,
Vincent

**Comment by azumads** [comment]
https://doc.getqor.com/plugins/i18n.html

https://doc.getqor.com/plugins/l10n.html

**Comment by vincent178** [comment]
Sorry my issue is not complete, I'm saying the i18n, and with the code, it can't compile, with type error.

If you could pull my code, compile it, it will throw the error.

By the way, I already updated all qor related packages.

**Comment by vincent178** [comment]
the detail error msg: 
```
# github.com/vincent178/capellini/config/admin
config/admin/admin.go:34: cannot use db.DB (type *gorm.DB) as type *database.Config in argument to database.New
config/admin/admin.go:34: cannot use database.New(db.DB) (type *database.Provider) as type i18n.Backend in argument to i18n.New:
	*database.Provider does not implement i18n.Backend (missing DeleteTranslation method)
```

**Comment by vincent178** [comment]
perfect!, thanks, save my day!!!
