### ISSUE TITLE
l10n usage issue

### ISSUE THREAD

**Issue by vincent178** [qor/qor#206]
One issue with l10n that, if I add `l10n.Locale` to model, then, there's no way to see this model in admin panel,

can you please help on this?

minimal reproducible code below:

```
package main

import (
	"fmt"
	"net/http"

	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
	"github.com/qor/admin"
	"github.com/qor/l10n"
	"github.com/qor/qor"
)

// Create a GORM-backend model
type User struct {
	gorm.Model
	Name string
	l10n.Locale
}

func main() {
	DB, _ := gorm.Open("sqlite3", "demo.db")
	DB.AutoMigrate(&User{})

	// Initalize
	Admin := admin.New(&qor.Config{DB: DB})

	// Create resources from GORM-backend model
	Admin.AddResource(&User{})

	// Register route
	mux := http.NewServeMux()
	// amount to /admin, so visit `/admin` to view the admin interface
	Admin.MountTo("/admin", mux)

	fmt.Println("Listening on: 9001")
	http.ListenAndServe("localhost:9001", mux)
}
```

screenshot below:

<img width="1440" alt="screen shot 2017-07-27 at 10 59 26 am" src="https://user-images.githubusercontent.com/2183720/28652480-b9bfb52e-72ba-11e7-9094-013286c369a8.png">

**Comment by vincent178** [comment]
@jinzhu seems you have fix it, I will do more test and close it if there's no other issue.

**Comment by jinzhu** [comment]
thank you for your report, let me know if it still an issue.
