### ISSUE TITLE
Miss path oauth

### ISSUE THREAD

**Issue by a-jahanshahlo** [qor/qor#207]
when I try to compile project throw panic?
I guess missing some files or paths.

`config\config.go:9:2: cannot find package "github.com/qor/auth/oauth/github" in any of:
       *\github.com\qor\auth\oauth\github (from $GOROOT)`

**Comment by alexmironof** [comment]
folder `oauth` changed to `providers` after some updates, try to replace it in your imports

**Comment by alexmironof** [comment]
also `phone` and `password` moved there from root folder
