### ISSUE TITLE
Add QOR to awesome-go repo

### ISSUE THREAD

**Issue by kifirkin** [qor/qor#208]
Is there a way to add QOR to https://github.com/avelino/awesome-go list?
btw, There some quality checks :wink: 

Also GORM is there

**Comment by seffyroff** [comment]
You could add a PR to the list yourself, could you not?

**Comment by alexmironof** [comment]
I did it :sweat_smile:, but there some requirements, I don't know if QOR pass them...

**Comment by alexmironof** [comment]
https://github.com/avelino/awesome-go/pull/1563

**Comment by alexmironof** [comment]
qor/qor needs coverage to pass requirements for awesome list

**Comment by jinzhu** [comment]
@alexmironof thank you, I will add more tests.
