### ISSUE TITLE
Warning message "WARNING: AssetFS is used before overwrite it!"

### ISSUE THREAD

**Issue by cheavck** [qor/qor#209]
I tried to implement a router that allows requests to assets in public folder in my application. A warning message "WARNING: AssetFS is used before overwrite it!" always appears with debug stack trace when I run the app. However, the application runs just fine and the css files are loaded successfully by front-end. Could anyone please tell me what happens behind that message?
The following is the init function of my routes package that uses bindatafs.

    package routes

    func init() {
	RootMux = http.NewServeMux()
	RootMux.Handle("/auth/", auth.Auth.NewServeMux())

	app.Admin.MountTo("/admin", RootMux)
	router := chi.NewRouter()
	router.Get("/", controllers.HomeIndex)

	//RootMux.Handle("/system/", utils.FileServer(http.Dir(filepath.Join(config.Root, "public"))))
	assetFS := bindatafs.AssetFS.FileServer(http.Dir("public"), "javascripts", "stylesheets", "images", "dist", "fonts", "vendors")
	for _, path := range []string{"javascripts", "stylesheets", "images", "dist", "fonts", "vendors"} {
		RootMux.Handle(fmt.Sprintf("/%s/", path), assetFS)
	}

	WildcardRouter := wildcard_router.New()
	WildcardRouter.MountTo("/", RootMux)
	WildcardRouter.AddHandler(router)
    }

**Comment by buurzx** [comment]
@cheavck  I'm getting the same till moved up this line  "my_app/config/admin/bindatafs" in my main.go import.

**Comment by cheavck** [comment]
:-O Surprisingly it works. I had given up integrating bindatafs until I followed you moving up the bindatafs import straight up. Thank you!

**Comment by cryptix** [comment]
I find the use of all those global variables and `init()` package functions quite bewildering. No wonder this isn't straight forward to use.
