### ISSUE TITLE
Latest version of QOR admin crashes

### ISSUE THREAD

**Issue by cheavck** [qor/qor#213]
I ran "go get -u" to update my QOR app and found that QOR admin shows 404 error when I perform the deletion. Please check the attached screen

<img width="1280" alt="screen shot 2017-10-31 at 6 08 57 pm" src="https://user-images.githubusercontent.com/8447074/32221205-395b7aaa-be67-11e7-9990-3e53df575524.png">

**Comment by cheavck** [comment]
Thank you very much for your fast response. 
PS: We are the golang developer team in Cambodia. We found QOR sdk is very helpful and useful in building the fast CMS. We have used Golang as backoffice and Angular2 as front-end for a year already. We have also introduced and boosted QOR and GORM in Cambodia tech community. Once again thank for your great work.

**Comment by jasonweng** [comment]
Hi @cheavck 

I just fixed this bug, Please update `admin` module. 

It's caused by AJAX handle 302 redirector bug.

**Comment by cheavck** [comment]
It works fine now. Thank @jasonweng.
