### ISSUE TITLE
怎么安装？文档里面找不到如何安装呢？

### ISSUE THREAD

**Issue by MariaWf** [qor/qor#219]
怎么安装？文档里面找不到如何安装呢？
怎么安装？文档里面找不到如何安装呢？
怎么安装？文档里面找不到如何安装呢？

**Comment by raven-chen** [comment]
就是按照 Golang 的标准方式安装依赖的包就可以

文档见这里. https://doc.getqor.com/guides/authentication.html "Quick Start" 部分.
