### ISSUE TITLE
use Go module install dependency package， /admin request error

### ISSUE THREAD

**Issue by ZetaChow** [qor/qor#240]
I use go.mod to install dependency package
build successful, but an error occurred while requesting /admin

if go get github/qor/... ， everything is ok
if install the package use 'go.mod', error occurred.

`2019/03/17 01:24:17 http: panic serving [::1]:50992: runtime error: invalid memory address or nil pointer dereference
goroutine 67 [running]:
net/http.(*conn).serve.func1(0xc00024e500)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x4658c00, 0x4b7dc70)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:95 +0x2e
html/template.(*Template).Execute(0x0, 0x47c8c40, 0xc0001b60e0, 0x46de140, 0xc00013e3f0, 0x1, 0xc0002327a0)
	/usr/local/go/src/html/template/template.go:119 +0x2f
github.com/qor/admin.(*Context).Execute(0xc00013e3f0, 0x46e1a5e, 0x5, 0xc0001ae2c0, 0xc00000ed60)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/context.go:227 +0x22c
github.com/qor/admin.(*Controller).Index.func1()
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/controller.go:37 +0x51
github.com/qor/responder.(*Responder).Respond(0xc0000d37c0, 0xc0001a6000)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/responder@v0.0.0-20171031032654-b6def473574f/responder.go:77 +0x236
github.com/qor/admin.(*Controller).Index(0xc0002420b0, 0xc00013e3f0)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/controller.go:40 +0x297
github.com/qor/admin.(*Admin).NewServeMux.func2(0xc00013e3f0, 0xc00014fc20)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:176 +0x202
github.com/qor/admin.Middleware.Next(...)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:37
github.com/qor/admin.(*Admin).NewServeMux.func1(0xc00013e3f0, 0xc00014fbe0)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:166 +0x119
github.com/qor/admin.Middleware.Next(...)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:37
github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc00013e3f0, 0xc00014e3e0)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/composite_primary_key_callback.go:27 +0x251
github.com/qor/admin.(*serveMux).ServeHTTP(0xc0004aa4d8, 0x47d2440, 0xc0001b60e0, 0xc0001a6000)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:267 +0x52c
net/http.(*ServeMux).ServeHTTP(0xc0004acb80, 0x47d2440, 0xc0001b60e0, 0xc0001a6000)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0003ac750, 0x47d2440, 0xc0001b60e0, 0xc0001a6000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00024e500, 0x47d3640, 0xc00022e2c0)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
2019/03/17 01:25:17 Finish [GET] /admin/products Took 0.29ms
2019/03/17 01:25:17 http: panic serving [::1]:51017: runtime error: invalid memory address or nil pointer dereference
goroutine 49 [running]:
net/http.(*conn).serve.func1(0xc00014c320)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x4658c00, 0x4b7dc70)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:95 +0x2e
html/template.(*Template).Execute(0x0, 0x47c8c40, 0xc0001162a0, 0x46de140, 0xc000124b60, 0x1, 0xc0003b0660)
	/usr/local/go/src/html/template/template.go:119 +0x2f
github.com/qor/admin.(*Context).Execute(0xc000124b60, 0x46e1a5e, 0x5, 0xc0001ae2c0, 0xc00014fd00)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/context.go:227 +0x22c
github.com/qor/admin.(*Controller).Index.func1()
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/controller.go:37 +0x51
github.com/qor/responder.(*Responder).Respond(0xc0003557c0, 0xc00057c400)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/responder@v0.0.0-20171031032654-b6def473574f/responder.go:77 +0x236
github.com/qor/admin.(*Controller).Index(0xc0002420b0, 0xc000124b60)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/controller.go:40 +0x297
github.com/qor/admin.(*Admin).NewServeMux.func2(0xc000124b60, 0xc00014fc20)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:176 +0x202
github.com/qor/admin.Middleware.Next(...)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:37
github.com/qor/admin.(*Admin).NewServeMux.func1(0xc000124b60, 0xc00014fbe0)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:166 +0x119
github.com/qor/admin.Middleware.Next(...)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:37
github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc000124b60, 0xc00014e3e0)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/composite_primary_key_callback.go:27 +0x251
github.com/qor/admin.(*serveMux).ServeHTTP(0xc0004aa4d8, 0x47d2440, 0xc0001162a0, 0xc00057c400)
	/Users/zetachow/workspace/go/pkg/mod/github.com/qor/admin@v0.0.0-20190315024238-4fd31f9f6cef/route.go:267 +0x52c
net/http.(*ServeMux).ServeHTTP(0xc0004acb80, 0x47d2440, 0xc0001162a0, 0xc00057c400)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0003ac750, 0x47d2440, 0xc0001162a0, 0xc00057c400)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00014c320, 0x47d3640, 0xc0001aea40)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
`

**Comment by andrioid** [comment]
Same here. Took the getting started snippet, did a "go mod init && go get -u ./... && go run main.go" and it crashes on the /admin call.

I tried this on another Linux machine the other day without issue, so maybe this is a regression.

**Comment by andrioid** [comment]
Looks similar to https://github.com/qor/qor/issues/202

**Comment by ZetaChow** [comment]
The problem is solved

copy `$GOPATH/qor/admin/views` to  `{current_path}/app/views/qor`

> When QOR Admin render pages, it looks up templates with AssetFS.
> A default implemention of AssetFS is looking up templates from the filesystem with pre-registered > view paths.
> it includes:
> {current_path}/app/views/qor
> {current_path}/vendor/github.com/qor/admin/views
> $GOPATH/src/github.com/qor/admin/views


https://doc.getqor.com/admin/theming_and_customization.html#themes

**Comment by andrioid** [comment]
Thank you @ZetaChow - This was very informative, because I had no idea what the cause was.

I'd like to propose:
- Adjusting the example to state that it will not work with Go modules.
- Maybe changing the default AssetFS so that it checks for go module paths and adds them to default for qor/admin. https://godoc.org/cmd/go/internal/modinfo maybe?
- Handling this error in a more graceful manner. It's quite hard to debug.

**Comment by ZetaChow** [comment]
I think that checks for go module paths and adds them to default for qor/admin  is a better way
