### ISSUE TITLE
No documentation comments

### ISSUE THREAD

**Issue by rogpeppe** [qor/qor#48]
To be a first class citizen in the Go ecosystem, all
exported functions, methods and types should have
appropriate documentation comments.

http://golang.org/doc/effective_go.html#commentary

No matter how good the documentation on the website is,
the godoc is the most important thing. Please document
this stuff!

**Comment by jinzhu** [comment]
Hi @rogpeppe 

We understand that, but the API is not freeze at that time (scheduled for September 2015), so we will do that before the finally launch.

**Comment by rogpeppe** [comment]
The API should be documented long, long before it's frozen.
Without documentation, I'm sorry to say it's essentially unusable.

**Comment by bodhi** [comment]
> Without documentation, I'm sorry to say it's essentially unusable.

Please don't be hyperbolic, it's not constructive.

We agree that the documentation is important, but we haven't been able to make time to look at it yet. As @jinzhu said, it's still very early stages for QOR.

**Comment by jinzhu** [comment]
@rogpeppe Thanks for your input… we will prioritize this higher and get these in soon

**Comment by mastrolinux** [comment]
I suggest to use golint that will help you filling proper comments for godoc.

**Comment by stuartweir** [comment]
Is there anything I would be able to do to help in the documentation of QOR? Any specific areas?

**Comment by jinzhu** [comment]
@stuartweir Thank you for that. If possible, it would be good to start from a new application, and document things that confuse you. (Sure, we are here to provide any help that you want)

**Comment by stuartweir** [comment]
No problem! Alright! I'll do that :+1:

**Comment by jinzhu** [comment]
We have added lots of documents, please review each component's readme and godoc
