### ISSUE TITLE
Be able to sorting selected options in multiple selector

### ISSUE THREAD

**Issue by junhuif** [qor/qor#92]
# Support sorting selected options in multiple selector
### Qor2 multiple selector component

![image](https://cloud.githubusercontent.com/assets/349931/9516595/3b9e5ca0-4cdc-11e5-9b4e-6224f5bb3e1c.png)

As the screenshot shows, the selected option has a `sort` icon, we drag the icon to sort the selected options.
### Qor3 multiple selector component

![image](https://cloud.githubusercontent.com/assets/349931/9516582/1baff64c-4cdc-11e5-9b7b-a60e3de282d0.png)

The above screenshot shows the current multiple selector component. It doesn't support sorting selected options yet.
## Feature requirement

Improve current multiple selector component in Qor3 to support sorting selected option like Qor2 provided.

**Comment by jasonweng** [comment]
You can use `sortable select many` module
