### ISSUE TITLE
Be able to sorting collection-edit item in collection-edit component

### ISSUE THREAD

**Issue by fengjh** [qor/qor#93]
# Feature requirement 

Made current Qor3 collection-edit component support sorting collection-edit item like Qor2 provided.

This is current Qor3 collection-edit component.

![image](https://cloud.githubusercontent.com/assets/349931/9516841/ea9ed92c-4cdd-11e5-8555-d18e72fc8f9a.png)

This is current Qor2 collection-edit component.

![image](https://cloud.githubusercontent.com/assets/349931/9516837/e077b450-4cdd-11e5-8f7d-205e99c790a6.png)

**Comment by ericwo** [comment]
<img width="747" alt="screen shot 2016-07-11 at 2 45 04 pm" src="https://cloud.githubusercontent.com/assets/1955079/16722001/3172d9f0-4776-11e6-8b05-624cbd46128e.png">

It is supported now.
